# Generated by Django 4.2 on 2023-05-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Нарды',
                'verbose_name_plural': 'Нарды',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Backgammon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('match_date', models.DateField()),
                ('time', models.TimeField()),
                ('image', models.ImageField(upload_to='nard_images/')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nard.sporttype')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nard.tournament')),
            ],
        ),
    ]
