# Generated by Django 4.2 on 2023-05-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nard', '0003_backgammon_name_alter_backgammon_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgammon',
            name='image',
            field=models.ImageField(default='default_image.jpg', null=True, upload_to='nard_images/'),
        ),
        migrations.AlterField(
            model_name='backgammon',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
