# Generated by Django 4.2 on 2023-05-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nard', '0004_alter_backgammon_image_alter_backgammon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgammon',
            name='image',
            field=models.ImageField(default='nardy-youtube-13_03_23-600x350.jpg', null=True, upload_to='nard_images/'),
        ),
        migrations.AlterField(
            model_name='backgammon',
            name='name',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
