# Generated by Django 4.2 on 2023-05-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Формы обратной связи'},
        ),
    ]
