# Generated by Django 4.2 on 2023-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_live',
            field=models.BooleanField(default=False),
        ),
    ]
