# Generated by Django 4.2 on 2023-05-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
