# Generated by Django 4.2 on 2023-06-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('img', models.ImageField(upload_to='services_img')),
            ],
        ),
    ]
