# Generated by Django 4.2 on 2023-05-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0002_alter_match_options_alter_sporttype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='sport_type_en',
        ),
        migrations.RemoveField(
            model_name='match',
            name='sport_type_ru',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament_en',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament_ru',
        ),
        migrations.RemoveField(
            model_name='sporttype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sporttype',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='team',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='gender_en',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='gender_ru',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='sport_type_en',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='sport_type_ru',
        ),
    ]
