# Generated by Django 4.2 on 2023-05-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0003_remove_match_sport_type_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='img',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
    ]
