# Generated by Django 4.2 on 2023-05-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0004_match_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='img',
            field=models.URLField(),
        ),
    ]
