# Generated by Django 4.2 on 2023-05-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0008_rename_img_match_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='match_date',
        ),
        migrations.AddField(
            model_name='match',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
