# Generated by Django 4.2 on 2023-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0010_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporttype',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
