# Generated by Django 4.2 on 2023-05-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0011_alter_sporttype_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
