# Generated by Django 4.2 on 2023-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0013_remove_match_youtube_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='image',
            field=models.ImageField(null=True, upload_to='match_images/'),
        ),
    ]
