# Generated by Django 4.2 on 2023-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0014_alter_match_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='image',
            field=models.ImageField(default='null', upload_to='match_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sporttype',
            name='logo',
            field=models.ImageField(blank=True, upload_to='sport_type_logo/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to='team_logo/'),
        ),
    ]
