# Generated by Django 4.2 on 2023-05-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_matches', '0015_alter_match_image_alter_sporttype_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporttype',
            name='logo',
            field=models.ImageField(upload_to='sport_type_logo/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='team_logo/'),
        ),
    ]
